add workflows, main.go and docker-compose.yml
ConduitIO/conduit-processor-template pull request #2
Opened 2024-10-16 00:04 UTC by AdamHaffar

2024-10-18 16:50 UTC, lovromazgon commented
Generally looks ok, I'm figuring out some minor details, specifically what it makes sense to showcase as the default processor, probably one that is simply passing records through.

2024-10-22 16:41 UTC, raulb requested changes

2024-10-22 16:41 UTC, raulb commented on README.md
> +3. Set up [automatic Dependabot PR merges](#automatically-merging-dependabot-prs).a
```suggestion
3. Set up [automatic Dependabot PR merges](#automatically-merging-dependabot-prs).
```

2024-10-22 16:41 UTC, raulb commented on README.md
> +* A [GitHub workflow](/.github/workflows/build.yml) to build the code and run the tests.
We don't seem to have a build.yml

2024-10-22 16:41 UTC, raulb commented on README.md
> +[merges minor version upgrades](/.github/workflows/dependabot-auto-merge-go.yml) automatically.
We don't have this one either.

2024-10-22 17:30 UTC, lovromazgon commented on README.md
> +* A [GitHub workflow](/.github/workflows/build.yml) to build the code and run the tests.
Good catch that was renamed to `test.yml`, we need to update it in the connector template as well.

2024-10-22 17:33 UTC, lovromazgon commented on README.md
> +[merges minor version upgrades](/.github/workflows/dependabot-auto-merge-go.yml) automatically.
This file is actually added as part of this PR (see https://github.com/ConduitIO/conduit-processor-template/blob/workflows/.github/workflows/dependabot-auto-merge-go.yml).

2024-10-23 10:25 UTC, raulb commented on README.md
> +[merges minor version upgrades](/.github/workflows/dependabot-auto-merge-go.yml) automatically.
I see. I only checked this branch, and main. My recommendation is update the README on that PR directly so we don't provide incomplete information until that PR is shipped.

2024-10-23 10:27 UTC, raulb approved these changes
Only one nit left.

2024-10-23 10:28 UTC, lovromazgon commented on README.md
> +[merges minor version upgrades](/.github/workflows/dependabot-auto-merge-go.yml) automatically.
Both are in this PR 🤔

2024-10-23 10:32 UTC, raulb commented on README.md
> +[merges minor version upgrades](/.github/workflows/dependabot-auto-merge-go.yml) automatically.
Oh weird! I completely missed it. I actually thought they were different branches 🤦🏻‍♂️

2024-10-23 10:34 UTC, merged